platform:ios,'7.0'
#pod 'JPushSDK'
#pod 'BaiduMapAPI', '~> 2.8.1'
#pod 'BaiduMapKit', '~> 2.9.0.2'
pod 'BaiduMapKit' #百度地图SDK
pod 'JMessage', '~> 1.0.6'
#pod 'Canvas', '~> 0.1.2'
#pod 'AFNetworking'
#pod 'MBProgressHUD'
#pod 'SVProgressHUD'
#, '~> 1.1.3'
#pod 'SDWebImage', '~>3.7'
#pod 'UMeng', '~> 2.2.1'
#pod 'UMengSocial', '~> 4.2.3'
#pod 'UMengMessage', '~> 1.1.0.2'
#pod 'UMengFeedback', '~> 2.3.4'
#pod 'UMengAppNetwork', '~> 3.5.6'
#pod 'UMengAnalytics', '~> 3.5.16'
pod 'ZSSRichTextEditor', '~> 0.5.2.1'
#pod 'RichEditorView', '~> 2.0.1'

## 主模块(必须)
#pod 'ShareSDK2'
## 短信(可选)
#pod 'ShareSDK2/Connection/SMS'
#pod 'SMS_SDK', '~> 1.1.1'
pod 'SMS-For-iOS', '~> 1.2.0'
